### ISSUE TITLE
Adaptive radius with storage quota

### ISSUE THREAD

**Issue by kdeme** [status-im/nimbus-eth1#1044]
With the ContentDB API additions of "get n furthest elements" and "get db size" the cli option of "--storage-size" can be added.

This probably means something like:
- cli argument to set the max. storage size
- Prune the db when max storage size is (almost) hit
- Pruning should remove furthest (from local id) elements in the content db first and lower the Radius. Probably want to do the exact calculation here on radius vs elements removed, with some margin.

I don't think we ever need to increase the radius again? If so there probably need some hysteresis control.

The current "debug" cli option that statically sets the radius should still remain there and also take precedence over the storage size option.

**Comment by KonradStaniec** [comment]
Initial version implemented by:
https://github.com/status-im/nimbus-eth1/pull/1079
https://github.com/status-im/nimbus-eth1/pull/1065
