### ISSUE TITLE
Get content for the history network into a file(s) in some format

### ISSUE THREAD

**Issue by kdeme** [status-im/nimbus-eth1#1083]
Currently some json files exist that hold block header and bodies.

We need new versions of these files that contain:
- Block header
- Block body
- receipts

Also, the way they are currently serialized is faulty and should be fixed (currently we need to re-serialize them because of this: https://github.com/status-im/nimbus-eth1/blob/master/fluffy/populate_db.nim#L69).

As a first step, we can keep the current format, and adjust the items above.
Secondly we could/should look into improving the current structure (e.g. with the current structure one can not iterate over a range of blocks from a file, however one can easily access one specific block based on hash). And perhaps also in the file format (e.g. something else than json, perhaps era alike?)

**Comment by KonradStaniec** [comment]
First part of the task fixed by - https://github.com/status-im/nimbus-eth1/pull/1115.

**Comment by kdeme** [comment]
As the first part is the most important part for now, I'll close this and create an issue specifically about storage format improvements.
