### ISSUE TITLE
Illegal storage access in the stack tests on 32-bit Windows

### ISSUE THREAD

**Issue by mratsim** [status-im/nimbus-eth1#11]
See: https://ci.appveyor.com/project/jarradh/nimbus/build/job/p87ff64h2h88x6hv#L1701

**Comment by coffeepots** [comment]
This might be the same issue I've encountered in #20.
Looks like it could be down to `bigEndianToInt` in `utils_numeric.nim`
```
proc bigEndianToInt*(value: Bytes): UInt256 =
  var bytes = value.padLeft(32, 0.byte)
  result = 0.u256
  for z in 0 ..< 4:
    var temp = 0.uint
    bigEndian64(temp.addr, bytes[24 - z * 8].addr) # here
    result.table[z] = temp
```
In 32 bit, the `addr` is causing the SIGSEGV, but it only seems to happen in VCC for me.
