### ISSUE TITLE
Lax syntax check with `new(T: type XXX, args ...)` prototyping

### ISSUE THREAD

**Issue by mjfh** [status-im/nimbus-eth1#1104]
Unless I got something wrong and this issue is already known, the following code compiles with `nim 1.2.16`
```
type
  MyObj1 = object
  MyObj2 = object

proc new(T: type MyObj1, o1arg1: int, o1arg2 = false): T = T()
proc new(T: type MyObj2, o2arg1: int, o2arg2: bool): T = T()

proc doesCompile =
  let a1 = MyObj1.new()    # should throw a compiler error
  let b1 = MyObj1.new(1)
  let c1 = MyObj1.new(1,false)
  let a2 = MyObj2.new()    # should throw a compiler error
  let c2 = MyObj2.new(1,false)

# proc doesNotCompile =
#   let b2 = MyObj2.new(1)
```
To my understanding, the assignments for `a1` and `a2` should not compile. This somehow defies the use of `MyObj1.new()` as opposed to `newMyObj1()` which behaves correctly.

**Comment by jangko** [comment]
The compiler is using `system.new` for `a1` and `a2`.

**Comment by mjfh** [comment]
> The compiler is using `system.new` for `a1` and `a2`.

Of course, stupid -- should have seen that.

On a second thought, I wonder about the wisdom of prototyping when defining a `new()` operator overloading `system.new()` as opposed to `newMyObj()`. To me, the former overloaded `new()` is more appealing but less less safe and comes for a price, see [Style Guide](https://status-im.github.io/nim-style-guide/language.objconstr.html?highlight=new#object-construction-languageobjconstr).

Using
```
type
  MyObj1Ref = ref MyObj1
proc init(T: type MyObj1Ref; ...) : T  =
  ...
 ```
seems safe (just realising that the style guide suggests `init()` rather than `new()` here.)
