### ISSUE TITLE
Support the Ultra Light Client (ULC) usage scenario

### ISSUE THREAD

**Issue by zah** [status-im/nimbus-eth1#111]
ULC will be the most lightweight client mode available in the Ethereum world before the introduction of Stateless clients. The premise is that block headers can be obtained from a trusted set of non-colluding servers (M our of N threshold is required) and then the LES protocol can be used to obtain specific state fragments and their corresponding merkle proofs. It is developed by our fellow Status contributors Boris Petrov (@b00ris) and Eugene Danilenko (@JekaMas).

Introduction:
https://www.youtube.com/watch?v=Z6UUT1TqdTs&t=0s&list=PLbrz7IuP1hrgIT5FK2emIMm410oLEFlXO&index=4

Some notes and plans published by Felföldi Zsolt:
https://gist.github.com/zsfelfoldi/bd618cbe0b529849abd692694ee11433
https://gist.githubusercontent.com/zsfelfoldi/7da2b802824569d2d159d5d06eeda14c/raw/faa3f18eb2d6f10aed84abbdb4c08a16f1c7a5c3/ulc.txt

An implementation branch based on go-ethereum:
https://github.com/status-im/go-ethereum/commits/enhancement/48/ulc_mode_rebase

**Comment by arnetheduck** [comment]
ULC obsolete

**Comment by JekaMas** [comment]
Hello guys! Surprised that it's still somewhere alive )
