### ISSUE TITLE
Build binary that imports nimbus-eth2 light client

### ISSUE THREAD

**Issue by kdeme** [status-im/nimbus-eth1#1161]
This should be seen as a first, introductory,  step for starting work on Nimbus light proxy:
- [x] Add Nimbus-eth2 repo to nimbus-eth1 vendor modules
- [x] Create a simple binary in nimbus-eth1 that currently does not do more than just import a light client module (e.g. https://github.com/status-im/nimbus-eth2/blob/stable/beacon_chain/light_client.nim or so) and compiles.

**Comment by kdeme** [comment]
First item done by https://github.com/status-im/nimbus-eth1/commit/1e4f138574215fd796ab9f00a335991ba19153e0

**Comment by KonradStaniec** [comment]
second item done by - https://github.com/status-im/nimbus-eth1/pull/1202
