### ISSUE TITLE
Implement Block Number - Block hash mapping from History network accumulators

### ISSUE THREAD

**Issue by kdeme** [status-im/nimbus-eth1#1163]
This is a similar issue as: https://github.com/status-im/nimbus-eth1/issues/1045, but it allows only for block number to hash mapping, not transactions.

This issue however does not require a canonical indices network, as we can shortcut this functionality by requesting accumulator data from the history network fairly easy.

**Comment by KonradStaniec** [comment]
implemented by https://github.com/status-im/nimbus-eth1/pull/1182
