### ISSUE TITLE
Crash when using --custom-network option

### ISSUE THREAD

**Issue by hmel** [status-im/nimbus-eth1#1180]
Master @ https://github.com/status-im/nimbus-eth1/commit/a5d4759bfd060ef379aca09b3152f6d9c8087e8c 
This crash occurs on startup when using the --custom-network command line option.
```Traceback (most recent call last, using override)
nimbus-eth1/nimbus/nimbus.nim(439) nimbus
nimbus-eth1/nimbus/nimbus.nim(378) start
nimbus-eth1/nimbus/nimbus.nim(135) setupP2P
nimbus-eth1/nimbus/p2p/chain/chain_desc.nim(209) newChain
nimbus-eth1/nimbus/p2p/chain/chain_desc.nim(170) initChain
nimbus-eth1/nimbus/p2p/chain/chain_desc.nim(150) setForkId
nimbus-eth1/vendor/nimbus-build-system/vendor/Nim/lib/pure/collections/tables.nim(664) toGenesisHeader
nimbus-eth1/vendor/nimbus-build-system/vendor/Nim/lib/system/excpt.nim(610) signalHandler
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```
I have bisected it to this commit: https://github.com/status-im/nimbus-eth1/commit/a087d655429b3c2db903e44cd514fac13a0dd636

**Comment by jangko** [comment]
I can reproduce the crash using config file without genesis. Is that what happened to you too? Or a combination of command line options?

**Comment by hmel** [comment]
I use this file https://github.com/status-im/nimbus-eth2/blob/unstable/scripts/nimbusel_genesis.json 
It used to work before the referenced commit.

**Comment by jangko** [comment]
nimbus-eth1 actually requires config file a bit different compared to geth. the above json file will not work with nimbus without modification. you need to group the genesis into "genesis" object. see examples in [here](https://github.com/status-im/nimbus-eth1/tree/master/tests/customgenesis).

But it confirms my suspicion.
