### ISSUE TITLE
Implement dispatching to forked ops

### ISSUE THREAD

**Issue by zah** [status-im/nimbus-eth1#123]
#### 1) Modify the current opcode table to include the following information

a) opcode number
b) opcode name
c) forks where the opcode was changed

For example, it can look like this:

```nim
opcodeTable:
  0x11 sdiv
  0x12 create [Tangerine, Spurious]
```

#### 2) Introduce a `forkedOp` macro

This will be similar to the current `op` macro, but creating a proc with an additional static enum parameter called `fork`.

``` nim
forkedOp create:
  when fork >= Tangerine:
    ...
```

#### 3) Compile the VM instruction dispatching loop for each fork

This will consult the opcodeTable and it will place calls to the forked procs using the correct static parameters. The information in the table is enough to ensure that only the minimal number of instantiations are created (i.e. only 3 versions of `create` are needed - "Initial", "After Tangerine" and "After Spurious")

#### 4) Make sure the block validation logic uses the correct dispatching loop depending on the block number

**Comment by zah** [comment]
I think we only need a way to specify that a certain opcode was introduced in certain fork. Then the single opcode table will still be enough to figure out that this particular opcode is not valid in the Genesis block.

The only strong assumption of the single opcode table is that opcodes won't change their numeric IDs across forks, which is a reasonable assumption.

**Comment by jangko** [comment]
I believe we can close this issue, our current evm have solve this, although not using macro.
