### ISSUE TITLE
Integrate Nimbus in Go EVMLab

### ISSUE THREAD

**Issue by zah** [status-im/nimbus-eth1#1245]
[Go EVMLab](https://github.com/holiman/goevmlab) is a project implementing differential fuzzing of EVM implementations (running the same code in multiple EVMs, and aiming to get a different result or potentially a crash).

Currently, it reuses the format of the [Ethereum state tests](https://github.com/ethereum/tests/tree/develop/GeneralStateTests) which are already supported by Nimbus and expects each client to produce an EVM execution trace (also, already supported by Nimbus).

We need to develop a custom binary conforming to the expectations of the EVMLab fuzzing tool and implement a `nimbus.go` integration module calling our binary here:

https://github.com/holiman/goevmlab/tree/master/evms

* [x] Build the custom binary through a new Makefile target
* [x] Submit a PR in the Go Evmlab repo

**Comment by jangko** [comment]
The first half part is done.

**Comment by jangko** [comment]
fixed by holiman/goevmlab#77, closing
