### ISSUE TITLE
nimbus t8n 0-touch reward on pre EIP150 networks

### ISSUE THREAD

**Issue by winsvega** [status-im/nimbus-eth1#1336]
Nimbus t8n tool also happen to have this issue:

on pre <=EIP150 networks if coinbase account get 0 mining reward (in state tests, or gasPrice = 0 in blockchain tests)
the account is still expected to be created in the post state as empty

```
Running test State Diff: (stExample/eip1559, fork: EIP150, TrInfo: d: 0, g: 0, v: 0, TrData: ` :raw 0x00..`) 
{
    "NEW: 0x2adc25665018aa1fe0e6bc666dac8fc2697ff9ba" : {
        "code" : "0x",
        "nonce" : "0x00 (0)",
        "balance" : "0x00 (0)",
        "storage" : {
        }
    }
}

```

nimbust t8n tool didn't put an account.

**Comment by jangko** [comment]
@winsvega: can you share your test vector with me? I have difficulty to reproduce it

**Comment by winsvega** [comment]
Here is the Nimbus log. 
https://justpaste.it/ceztv

the transaction that comes is invalid. this is experimental test to check exceptions of rlp transaction sturctures in state tests too. the transaction supposed to be rejected with exception and the mine_block just seals an empty block.
