### ISSUE TITLE
allow Legacy Sync to sync with available peers instead of waiting for minimal amount of peers after a period of time

### ISSUE THREAD

**Issue by jangko** [status-im/nimbus-eth1#1385]
Legacy it is, but it still useful to test out experimental features before ported to other sync algorithm.

Current Legacy Sync design requires minimal two peers before syncing started, but the hive test(ethereum/sync) only provide one peers to sync with.

reference implementation starts with min 5 peers before syncing started, but after a period of time passed, and the minimal amount of peers not meet, it will start syncing with available number of peers.

This will require significant amount of work to redesign Legacy Sync. But because other sync algorithm also not ready to participate in hive test, the experiment should be first tested in Legacy Sync.

**Comment by tersec** [comment]
Legacy sync was removed: https://github.com/status-im/nimbus-eth1/pull/2237
