### ISSUE TITLE
Implement EIPs for Shanghai fork

### ISSUE THREAD

**Issue by AdamSpitz** [status-im/nimbus-eth1#1399]
- [ ] [EIP-3540](https://eips.ethereum.org/EIPS/eip-3540): EVM Object Format (EOF) v1
- [x] [EIP-3651](https://eips.ethereum.org/EIPS/eip-3651): Warm COINBASE
- [ ] [EIP-3670](https://eips.ethereum.org/EIPS/eip-3670): EOF - Code Validation
- [x] [EIP-3855](https://eips.ethereum.org/EIPS/eip-3855): PUSH0 instruction
- [x] [EIP-3860](https://eips.ethereum.org/EIPS/eip-3860): Limit and meter initcode
- [ ] [EIP-4200](https://eips.ethereum.org/EIPS/eip-4200): EOF - Static relative jumps
- [ ] [EIP-4750](https://eips.ethereum.org/EIPS/eip-4750): EOF - Functions
- [ ] [EIP-4895](https://eips.ethereum.org/EIPS/eip-4895): Beacon chain push withdrawals as operations
- [ ] [EIP-5450](https://eips.ethereum.org/EIPS/eip-5450): EOF - Stack Validation

(The list comes from [here](https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/shanghai.md#included-eips).)

**Comment by jangko** [comment]
fixed by #1509, closing. EOF suite are moved to Cancun.
