### ISSUE TITLE
Timestamp-based forking for Shanghai (and later)

### ISSUE THREAD

**Issue by AdamSpitz** [status-im/nimbus-eth1#1424]
Activation of the Shanghai fork will be determined by a timestamp, not a block number.

e.g. [EIP-4895](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-4895.md) says, "Beginning with the execution timestamp FORK_TIMESTAMP, execution clients MUST introduce the following extensions to payload validation and processing..."

jangko had some comments [here](https://github.com/status-im/nimbus-eth1/pull/1409) on how to go about implementing this.

  - We probably need both shanghaiBlock and shanghaiTime, because hive and ethereum/tests are still using a block number.
  - The relevant files are common/common.nim and hardforks.nim.

**Comment by AdamSpitz** [comment]
Note also that geth has put in a hard-coded value called timestampThreshold, used to decide whether a forkid.next field is a block number or a timestamp.

https://github.com/ethereum/go-ethereum/blob/master/core/forkid/forkid.go#L48

**Comment by jangko** [comment]
in EIP-4895, geth still keep both `shanghaiBlock` and `shanghaiTime`. but in EIP-4844, as can be seen in this [commit](https://github.com/mdehoog/go-ethereum/commit/b2d6f07276f6cb3cf9e306333eab56fc54324f9c), they remove `shanghaiBlock` and use only timestamp.
Sure this will complicated fork transition and forkid calculation.

**Comment by jangko** [comment]
fixed by #1465. closing
