### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by yanrising** [status-im/nimbus-eth1#1463]
Ububntu 18. All depencies are installed. RocksDB installed. Prerequisites via nix-shell default.nix installed without errors.

dagen@ubuntu:~/projects/nimbus-eth1$ sudo make nimbus
[sudo] password for dagen: 

Tip of the day: this will probably build faster if you use "make -j2 ...".

Building: Nim compiler
Building: install/usr/lib/libbacktrace.a
Building: install/usr/lib/libbacktracenim.a
Building: build/nimbus
/home/dagen/projects/nimbus-eth1/nimbus/nimbus.nim(1, 2) Error: cannot open file: ""
Makefile:165: recipe for target 'nimbus' failed
make: *** [nimbus] Error 1

**Comment by jangko** [comment]
$> make update deps
$> make nimbus

**Comment by yanrising** [comment]
1. git clone new source - git clone https://github.com/status-im/nimbus-eth1.git
2. git submodule update --init --recursive
3. make update deps
Result:
dagen@ubuntu:~/projects/nimbus-eth1$ make update deps
Creating nimbus-build-system.paths
fatal: No url found for submodule path 'vendor/nim-snappy/tests/snappycpp/third_party/benchmark' in .gitmodules
Failed to recurse into submodule path 'vendor/nim-snappy/tests/snappycpp'
fatal: No url found for submodule path 'vendor/nimbus-eth2/vendor/nim-bearssl/bearssl/csources' in .gitmodules
fatal: No url found for submodule path 'vendor/nimbus-eth2/vendor/nim-blscurve/vendor/blst' in .gitmodules
fatal: No url found for submodule path 'vendor/nimbus-eth2/vendor/nim-libbacktrace/vendor/libbacktrace-upstream' in .gitmodules
fatal: No url found for submodule path 'vendor/nimbus-eth2/vendor/nim-nat-traversal/vendor/libnatpmp-upstream' in .gitmodules
fatal: No url found for submodule path 'vendor/nimbus-eth2/vendor/nim-secp256k1/secp256k1_wrapper/secp256k1' in .gitmodules
fatal: No url found for submodule path 'vendor/nimbus-eth2/vendor/nim-snappy/tests/snappycpp' in .gitmodules
fatal: No url found for submodule path 'vendor/nimbus-eth2/vendor/nim-zlib/zlib/csources' in .gitmodules
fatal: No url found for submodule path 'vendor/nimbus-eth2/vendor/nimbus-build-system/vendor/Nim' in .gitmodules
Failed to recurse into submodule path 'vendor/nimbus-eth2/vendor/nim-bearssl'
Failed to recurse into submodule path 'vendor/nimbus-eth2/vendor/nim-blscurve'
Failed to recurse into submodule path 'vendor/nimbus-eth2/vendor/nim-libbacktrace'
Failed to recurse into submodule path 'vendor/nimbus-eth2/vendor/nim-nat-traversal'
Failed to recurse into submodule path 'vendor/nimbus-eth2/vendor/nim-secp256k1'
Failed to recurse into submodule path 'vendor/nimbus-eth2/vendor/nim-snappy'
Failed to recurse into submodule path 'vendor/nimbus-eth2/vendor/nim-zlib'
Failed to recurse into submodule path 'vendor/nimbus-eth2/vendor/nimbus-build-system'
Failed to recurse into submodule path 'vendor/nim-snappy'
Failed to recurse into submodule path 'vendor/nimbus-eth2'
fatal: No url found for submodule path 'vendor/nim-snappy/tests/snappycpp/third_party/benchmark' in .gitmodules
Failed to recurse into submodule path 'vendor/nim-snappy/tests/snappycpp'
fatal: No url found for submodule path 'vendor/nimbus-eth2/vendor/nim-bearssl/bearssl/csources' in .gitmodules
fatal: No url found for submodule path 'vendor/nimbus-eth2/vendor/nim-blscurve/vendor/blst' in .gitmodules
fatal: No url found for submodule path 'vendor/nimbus-eth2/vendor/nim-libbacktrace/vendor/libbacktrace-upstream' in .gitmodules
fatal: No url found for submodule path 'vendor/nimbus-eth2/vendor/nim-nat-traversal/vendor/libnatpmp-upstream' in .gitmodules
fatal: No url found for submodule path 'vendor/nimbus-eth2/vendor/nim-secp256k1/secp256k1_wrapper/secp256k1' in .gitmodules
fatal: No url found for submodule path 'vendor/nimbus-eth2/vendor/nim-snappy/tests/snappycpp' in .gitmodules
fatal: No url found for submodule path 'vendor/nimbus-eth2/vendor/nim-zlib/zlib/csources' in .gitmodules
fatal: No url found for submodule path 'vendor/nimbus-eth2/vendor/nimbus-build-system/vendor/Nim' in .gitmodules
Failed to recurse into submodule path 'vendor/nimbus-eth2/vendor/nim-bearssl'
Failed to recurse into submodule path 'vendor/nimbus-eth2/vendor/nim-blscurve'
Failed to recurse into submodule path 'vendor/nimbus-eth2/vendor/nim-libbacktrace'
Failed to recurse into submodule path 'vendor/nimbus-eth2/vendor/nim-nat-traversal'
Failed to recurse into submodule path 'vendor/nimbus-eth2/vendor/nim-secp256k1'
Failed to recurse into submodule path 'vendor/nimbus-eth2/vendor/nim-snappy'
Failed to recurse into submodule path 'vendor/nimbus-eth2/vendor/nim-zlib'
Failed to recurse into submodule path 'vendor/nimbus-eth2/vendor/nimbus-build-system'
Failed to recurse into submodule path 'vendor/nim-snappy'
Failed to recurse into submodule path 'vendor/nimbus-eth2'
vendor/nimbus-build-system/makefiles/targets.mk:107: recipe for target 'update-common' failed
make: *** [update-common] Error 1
dagen@ubuntu:~/projects/nimbus-eth1$

**Comment by jangko** [comment]
`$> make update deps` will handle the above problem
no need to call `git submodule update --init --recursive`, because we use specialized nimbus-eth2 submodules handling to not have duplicate submodules with nimbus-eth1
