### ISSUE TITLE
Nimbus t8n 4844 support

### ISSUE THREAD

**Issue by winsvega** [status-im/nimbus-eth1#1587]
as nimbus now is getting the best t8n implementation
to make tests around 4844 it would be good to have blob tx support.

in t8n reponse file 
"currentExcessDataGas" 
in env t8n file
"parentExcessDataGas" (to calculate the formula) or "currentExcessDataGas" (to set the value without formula)

**Comment by jangko** [comment]
Hai @winsvega , eip-4844 branch is ready for testing. Hope it works well because it's still fresh from the oven

**Comment by winsvega** [comment]
the result file does not have 
```
 "excessDataGas"
 "dataGasUsed"
```

also the tx is rejected with general message `"error": "processTransaction failed"`
so I don't know what is wrong

**Comment by jangko** [comment]
@winsvega , BlobHash bug fixed.
