### ISSUE TITLE
Why does `make t8n` require building the Nim compiler?

### ISSUE THREAD

**Issue by qbzzt** [status-im/nimbus-eth1#1665]
I installed Nim using https://nim-lang.org/install_unix.html. 

Still, when I try to `make t8n`, the first step is to build the Nim compiler. Why is it necessary when I already have the compiler? If it weren't necessary, I could build the `retesteth` Docker image a lot faster.

Alternatively, if you could provide a binary for Linux of Nimbus, that would solve the same problem even better.

```
qbzzt1@tests:~/nimbus-eth1$ nim --version
Nim Compiler Version 1.6.14 [Linux: amd64]
Compiled at 2023-06-27
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 71ba2e7f3c5815d956b1ae0341b0743242b8fec6
active boot switches: -d:release
qbzzt1@tests:~/nimbus-eth1$ make t8n

Tip of the day: this will probably build faster if you use "make -j2 ...".

Building: Nim compiler
^Cmake[1]: *** [vendor/nimbus-build-system/makefiles/targets.mk:81: build-nim] Interrupt
make: *** [vendor/nimbus-build-system/makefiles/targets.mk:124: vendor/nimbus-build-system/vendor/Nim/bin/nim] Interrupt
```

**Comment by jangko** [comment]
Newer Nim compiler version often introduce breaking changes or bugs. That's why we ship a specific version of nim compiler that works with all of nimbus-eth1 deps library.

In the readme, we provide various ways to build t8n tool. Not all of them need to build nim compiler, e.g. number 1.
And building the nim compiler via make only done once.
https://github.com/status-im/nimbus-eth1/blob/master/tools/t8n/readme.md

**Comment by qbzzt** [comment]
Thank you. I'll update the Dockerfile for `retesteth` to use that.

**Comment by qbzzt** [comment]
Sorry, it doesn't work for me - can you help me? Here are the commands I run:

```
sudo apt install -y g++ git librocksdb-dev make
wget https://nim-lang.org/choosenim/init.sh
chmod +x init.sh 
./init.sh -y
git clone --recursive https://github.com/status-im/nimbus-eth1.git nimbus
cd nimbus
nimble install -y --depsOnly
nim c -d:release -d:chronicles_default_output_device=stderr tools/t8n/t8n
```

The last command returns this error:

```
qbzzt1@tests2:~/nimbus$ nim c -d:release -d:chronicles_default_output_device=stderr tools/t8n/t8n
/home/qbzzt1/nimbus/config.nims(11, 11) Error: cannot open file: nimbus-build-system.paths
```

When I comment out that check it just fails with:

```
qbzzt1@tests2:~/nimbus$ nim c -d:release -d:chronicles_default_output_device=stderr tools/t8n/t8n
/home/qbzzt1/nimbus/tools/t8n/config.nims(1, 2) Error: cannot open file: ""
qbzzt1@tests2:~/nimbus$ nano config.nims
```

This is for a `Dockerfile`, so it has to be a one time thing. This is the reason it doesn't help that you only build the compiler the first time.

   Thanks,
       Ori

**Comment by jangko** [comment]
Ah, sorry. I forget about fluffy dependencies. Because fluffy and nimbus-verified-proxy have nimbus-eth2 as dependency, 
nimble cannot handle our complex dependency anymore. So we decide not to use nimble anymore and I forget to update the build instruction.

please run `./env.sh` once to generate the `nimbus-build-system.paths` and you can compile the project using your nim compiler.
but currently, because of nim compiler bugs in v1.6.14/v1.6.15, nimbus-eth1 only can be compiled by nim v1.6.12 (branch version-1-6 commit [1aa9273640c0c51486cf3a7b67282fe58f360e91](https://github.com/status-im/Nim/tree/1aa9273640c0c51486cf3a7b67282fe58f360e91)).

**Comment by qbzzt** [comment]
@jangko, it still doesn't work :-(

I put your instructions into the `Dockerfile`:

```
RUN test -n "$NIMBUS" \
     && apt-get update \
     && apt-get install --yes librocksdb-dev g++ make \
     && rm -rf /var/lib/apt/lists/* \
     && wget https://nim-lang.org/choosenim/init.sh \
     && chmod +x init.sh \
     && ./init.sh -y \
     && PATH=~/.nimble/bin:$PATH \
     && git clone $NIMBUS_SRC /nimbus \
     && cd /nimbus \
     && git submodule update --init --recursive \
     && ./env.sh \
     && nim c -d:release -d:chronicles_default_output_device=stderr tools/t8n/t8n \
     && cp /nimbus/tools/t8n/t8n /bin/evm_nimbus \
     && rm -rf /nimbus \
```

and it still fails:

```
Submodule path 'vendor/nimbus-eth2/vendor/sepolia': checked out 'b1c92d73fff96685c5deee7138670aa1f769890f'
Submodule path 'vendor/nimbus-security-resources': checked out 'ce9945b1b159d4c9b628f8c4cd2d262964692810'
Submodule path 'vendor/nimcrypto': checked out '24e006df85927f64916e60511620583b11403178'
Submodule path 'vendor/portal-spec-tests': checked out '529764e1df46f99899127b75097d5162e9ed7ed0'
Submodule path 'vendor/tempfile.nim': checked out '96fe74e69838c99641e4f7138c987d5f346c26f1'
/nimbus/vendor/nimbus-build-system/scripts/env.sh: line 29: cd: /nimbus/vendor/nimbus-build-system/scripts/../../.nimble: No such file or directory
/nimbus/tools/t8n/config.nims(1, 2) Error: cannot open file: ""
```

Any idea what I am missing?

**Comment by jangko** [comment]
Add `make deps-common nat-libs nimbus.nims` before invoking nim compiler. 
Our complex workaround for nimble and choosenim limitations gave birth to this insanity.

**Comment by qbzzt** [comment]
No good. I added `make deps-common nat-libs nimbus.nims` to the `Dockerfile`, and now it builds the nim compiler locally again:

```
Submodule path 'vendor/nimcrypto': checked out '24e006df85927f64916e60511620583b11403178'
Submodule path 'vendor/portal-spec-tests': checked out '529764e1df46f99899127b75097d5162e9ed7ed0'
Submodule path 'vendor/tempfile.nim': checked out '96fe74e69838c99641e4f7138c987d5f346c26f1'
/nimbus/vendor/nimbus-build-system/scripts/env.sh: line 29: cd: /nimbus/vendor/nimbus-build-system/scripts/../../.nimble: No such file or directory

Tip of the day: this will probably build faster if you use "make -j2 ...".

Building: Nim compiler
```

This is the relevant part of the `Dockerfile`:

```
RUN test -n "$NIMBUS" \
     && apt-get update \
     && apt-get install --yes librocksdb-dev g++ make \
     && rm -rf /var/lib/apt/lists/* \
     && wget https://nim-lang.org/choosenim/init.sh \
     && chmod +x init.sh \ 
     && ./init.sh -y \
     && PATH=~/.nimble/bin:$PATH \
     && git clone $NIMBUS_SRC /nimbus \
     && cd /nimbus \
     && git submodule update --init --recursive \
     && ./env.sh \
     && make deps-common nat-libs nimbus.nims \
     && nim c -d:release -d:chronicles_default_output_device=stderr tools/t8n/t8n \
     && cp /nimbus/tools/t8n/t8n /bin/evm_nimbus \
     && rm -rf /nimbus \
```

Do you see anything obviously wrong? If not, I think I'll give up on this and just accept that building the `retesteth` docker file with Nimbus takes a long time.

Can we make the latest binary available for download?

**Comment by jangko** [comment]
well, if you use choosenim, it will download a buggy nim compiler. you have to build our suggested nim version anyway.
until they fix nim compiler and nimble, things will be unnecessary complex for us.
