### ISSUE TITLE
Create a sharable debugging and testing environment for Ethereum

### ISSUE THREAD

**Issue by zah** [status-im/nimbus-eth1#172]
We can create a Vagrant recipe that simplifies the complex setup required for testing Nimbus against other Ethereum clients. 

Such a VM would provide a GUI environment where all kind of debugging and system monitoring tools are pre-installed (e.g. a pre-configured copy of VS Code with tools for debugging Parity, Geth and py-evm, tools such as Wireshark with additional [Ethereum-related dissectors](https://media.consensys.net/releasing-wireshark-dissectors-for-ethereum-%C3%B0%CE%BEvp2p-protocols-215c9656dd9c) and so on).

Over time, the shared effort to improve and document the capabilities of this environment is expected to pay out in increased productivity of the entire team.

**Comment by arnetheduck** [comment]
https://github.com/ethereum/hive is the official upstream project for these kinds of setup - can we contribute there instead?

**Comment by zah** [comment]
It seems to me that Hive could be a valuable addition to the environment I'm describing, but the relation is that the environment contains Hive and other debugging tools instead of the other way around. 

Hive is a project with a very specific and a bit more narrow goal. We should definitely contribute Nimbus support for it though.
