### ISSUE TITLE
Fluffy: Add client tag to ENR

### ISSUE THREAD

**Issue by KolbyML** [status-im/nimbus-eth1#1755]
Fluffy still doesn't have its client tagged in its enr. 

So the key is 'c' and the value is 'f'

For example Trins is 'c':'t' t for trin.

We currently have visuals on Glados what mak euse of this. Also there will soon be a client distrubition chart and currently fluffy is just labeled as unknown since it doesn't have the 'c' key set.

It would be nice to see fluffy instead of unknown!

**Comment by kdeme** [comment]
This issue is related to that: https://github.com/status-im/nimbus-eth1/issues/1643

Although we can probably get away with just the c:f key value without the git revision

**Comment by kdeme** [comment]
done in #1513
