### ISSUE TITLE
Compiler crash while compiling fluffy on Mac OS M1, nim 1.6.16

### ISSUE THREAD

**Issue by mynameisdaniil** [status-im/nimbus-eth1#1819]
I've created an issue for that in the nim-lang repo:
https://github.com/nim-lang/Nim/issues/22820
Branch under question: https://github.com/status-im/nimbus-eth1/tree/compiler-segfault

**Comment by tersec** [comment]
Does this still happen with Nim 1.6.20?

**Comment by tersec** [comment]
It does, https://github.com/nim-lang/Nim/issues/22820#issuecomment-2132460167

But unless there's another issue, fixed in newer Nim versions such as 2.0, so closing issue here. Reopen or create new issue if it's still truly present.
