### ISSUE TITLE
RPC calls to Fluffy nodes timeout randomly

### ISSUE THREAD

**Issue by jakubgs** [status-im/nimbus-eth1#1880]
Currently RPC calls to Fluffly nodes on our hosts randomly fail with timeouts:
```
admin@metal-01.ih-eu-mda1.nimbus.fluffy:/etc/consul % /data/nimbus-fluffy-mainnet-master-21/rpc.sh discv5_nodeInfo
curl: (28) Operation timed out after 5000 milliseconds with 0 bytes received
admin@metal-01.ih-eu-mda1.nimbus.fluffy:/etc/consul % /data/nimbus-fluffy-mainnet-master-21/rpc.sh discv5_nodeInfo
curl: (28) Operation timed out after 5000 milliseconds with 0 bytes received
admin@metal-01.ih-eu-mda1.nimbus.fluffy:/etc/consul % /data/nimbus-fluffy-mainnet-master-21/rpc.sh discv5_nodeInfo
curl: (28) Operation timed out after 5000 milliseconds with 0 bytes received
admin@metal-01.ih-eu-mda1.nimbus.fluffy:/etc/consul % /data/nimbus-fluffy-mainnet-master-21/rpc.sh discv5_nodeInfo
curl: (28) Operation timed out after 5001 milliseconds with 0 bytes received
admin@metal-01.ih-eu-mda1.nimbus.fluffy:/etc/consul % /data/nimbus-fluffy-mainnet-master-21/rpc.sh discv5_nodeInfo
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "enr": "enr:-Ia4QIqV-ew-weNHsWiX7N6pLptbzeaL6HaouE9X-81t9yFMBIWnbPEOumk2FX1yiw_KvbXuUkQsZmbgO4Lgcv13yaEBY2aCaWSCdjSCaXCEwiEo7olzZWNwMjU2azGhA0GU4pJVddsE_yTegaBcjtW71TRp4qYVST22Rbl-WB1lg3VkcIIjoQ",
    "nodeId": "0x67aeac203f4863ec1cc4bca130c2dc2f0374abaffd1f85ab24dc72669dd3ba1d"
  }
}
```
But then recover for no apparent reason. The host itself is not overloaded:

![image](https://github.com/status-im/nimbus-eth1/assets/2212681/fe8d3017-93f6-4111-bab5-3e9ed936d5b8)

And there's no sign of hitting any open sockets limits:

![image](https://github.com/status-im/nimbus-eth1/assets/2212681/25f85b06-4d8c-4dd9-8850-de64160c059e)
https://grafana.infra.status.im/d/QCTZ8-Vmk/single-host-dashboard?orgId=1&refresh=1m&var-host=metal-01.ih-eu-mda1.nimbus.fluffy&from=1698833493149&to=1698919893149

And yet RPC calls still randomly timeout.

**Comment by jakubgs** [comment]
If we look at 10 days of data for `metal-01.ih-eu-mda1.nimbus.fluffy` we can see a massive spike in load:

![image](https://github.com/status-im/nimbus-eth1/assets/2212681/13458ed8-705f-47aa-9a18-c564cdf8258a)

And a matching spike in disk I/O:

![image](https://github.com/status-im/nimbus-eth1/assets/2212681/d6ba16f1-18e9-448f-b645-9697a97d09fa)

But interestingly traffic handled is down:

![image](https://github.com/status-im/nimbus-eth1/assets/2212681/fb5b7b57-6e6a-460d-a6d7-707a921805e6)

**Comment by jakubgs** [comment]
Of course `linux-02` node shows the same symptoms:

![image](https://github.com/status-im/nimbus-eth1/assets/2212681/9c2bfdbd-9f52-44ba-991a-9910fad3a08d)

So I don't think this is host specific, and looks more like a bug to me.

**Comment by jakubgs** [comment]
If we look at a 30 day graph it seems to me like this started somewhere around 23rd of October:

![image](https://github.com/status-im/nimbus-eth1/assets/2212681/fe027420-baa2-4e90-8889-be7d33a44fec)

**Comment by jakubgs** [comment]
If we look at build logs we can see the version changes in time:
```
admin@metal-01.ih-eu-mda1.nimbus.fluffy:~ % j --since '30 days ago' -u build-nimbus-fluffy-mainnet-master | grep 'HEAD is now at'
Oct 06 00:00:03 metal-01.ih-eu-mda1.nimbus.fluffy build.sh[4030626]: HEAD is now at 43b6014f Further Portal beacon network improvements (#1808)
Oct 07 00:00:04 metal-01.ih-eu-mda1.nimbus.fluffy build.sh[107472]: HEAD is now at 7b313ec1 Use signature slot instead of attested header slot (#1811)
Oct 08 00:00:03 metal-01.ih-eu-mda1.nimbus.fluffy build.sh[370057]: HEAD is now at 7b313ec1 Use signature slot instead of attested header slot (#1811)
Oct 09 00:00:02 metal-01.ih-eu-mda1.nimbus.fluffy build.sh[620449]: HEAD is now at 7b313ec1 Use signature slot instead of attested header slot (#1811)
Oct 10 00:00:04 metal-01.ih-eu-mda1.nimbus.fluffy build.sh[877174]: HEAD is now at effe9c7a Implement safe and finalized tag for eth_getBlockByNumber (#1814)
Oct 11 00:00:04 metal-01.ih-eu-mda1.nimbus.fluffy build.sh[1143559]: HEAD is now at 00659bc1 Update README.md to fix link to portal specs (#1812)
Oct 12 00:00:04 metal-01.ih-eu-mda1.nimbus.fluffy build.sh[1405522]: HEAD is now at 786263c0 Core db update api and fix tracer methods (#1816)
Oct 15 00:00:03 metal-01.ih-eu-mda1.nimbus.fluffy build.sh[2223151]: HEAD is now at 1ffac5b2 Fudge persistent legacy hexary db edge case (#1817)
Oct 16 00:00:02 metal-01.ih-eu-mda1.nimbus.fluffy build.sh[2477710]: HEAD is now at 1ffac5b2 Fudge persistent legacy hexary db edge case (#1817)
Oct 17 00:00:04 metal-01.ih-eu-mda1.nimbus.fluffy build.sh[2728221]: HEAD is now at 750a075a nimbus-build-system: Bump Nim to version 1.6.16 (#1818)
Oct 20 00:00:10 metal-01.ih-eu-mda1.nimbus.fluffy build.sh[3528401]: HEAD is now at 14ee5f68 Clean-up/refactor in beacon lc db (#1830)
Oct 21 00:00:03 metal-01.ih-eu-mda1.nimbus.fluffy build.sh[3796965]: HEAD is now at 9563beea Don't send the processed bitlist if contentQueue is full (#1835)
Oct 22 00:00:24 metal-01.ih-eu-mda1.nimbus.fluffy build.sh[4059674]: HEAD is now at affc763d Bump eth-tests: Refill tests with Cancun spec
Oct 23 00:00:04 metal-01.ih-eu-mda1.nimbus.fluffy build.sh[128827]: HEAD is now at d1252665 Bump nim-eth: remove EIP-4844 blobs before hashing tx (#1840)
Oct 24 00:00:05 metal-01.ih-eu-mda1.nimbus.fluffy build.sh[390136]: HEAD is now at 77289c77 More cancun tests (#1843)
Oct 25 00:00:05 metal-01.ih-eu-mda1.nimbus.fluffy build.sh[653361]: HEAD is now at 6e59cccc Add more documentation to the fluffy book and reorganize it (#1856)
Oct 26 00:00:05 metal-01.ih-eu-mda1.nimbus.fluffy build.sh[918228]: HEAD is now at 3198ad1b Fix default pruning for ledger and update core db and ledger logging (#1861)
Nov 03 00:00:02 metal-01.ih-eu-mda1.nimbus.fluffy build.sh[3033366]: HEAD is now at 25bc8e4b Add blobGasPrice and blobGasUsed to ReceiptObject of RPC
```

**Comment by kdeme** [comment]
@jakubgs Thanks a lot for spotting this and further investigation. I'll have a look at which changes could cause this.

**Comment by kdeme** [comment]
After looking at the commit history, there aren't really any direct changes that are likely to cause this issue.
There are some vendor bumps but they are not really related to storage and there is a Nim minor version bump also, but I'm doubtful that this introduced some disk access bug.

I tried to look into actual Fluffy metrics but nothing stands out there either.
However, when checking the database sizes I noticed they increased a lot since last time (begin October) that I checked those. Looking at the metrics, there has indeed been a big increase of how much data got stored, and thus basically how much data got gossiped into the Portal network. It is kind of strange that this doesn't show up clearly in the network usage however.

![image](https://github.com/status-im/nimbus-eth1/assets/7857583/01fe656a-686b-4a48-be7b-aefcb2abc780)

**Comment by jakubgs** [comment]
Indeed, it could it be that the database size has big impact on performance and it's increase directly impacts the performance of queries in in turn increases I/O. Maybe we're missing an index and scanning the whole DB or something?

**Comment by kdeme** [comment]
> Indeed, it could it be that the database size has big impact on performance and it's increase directly impacts the performance of queries in in turn increases I/O. Maybe we're missing an index and scanning the whole DB or something?

Yes, I think something like that is likely the cause.
There are probably some performance improvements possible here, however, the nodes are actually storing a big chunk of the network. Considering other clients have increased their fleets since we started, I will first look into simply reducing the radius and store less data.

**Comment by kdeme** [comment]
I have pruned the databases with the added functionality of https://github.com/status-im/nimbus-eth1/pull/1896

![image](https://github.com/status-im/nimbus-eth1/assets/7857583/dd965315-957b-4233-b3a6-d39b7574c771)

Surprisingly, the disk utilization with appears even much lower than what I expected. Not fully sure how come, perhaps the repacking that the SQL vacuum (https://www.sqlite.org/lang_vacuum.html) does has to do with it.

@jakubgs Please let me know if the RPC timeouts still occur now or not.

**Comment by jakubgs** [comment]
Oh, and I lowered the alert thresholds to see what happens:

- [`infra-nimbus#6b800a53`](https://github.com/status-im/infra-nimbus/commit/6b800a53) - nimbus.fluffy: re-enable Consul healthchecks
