### ISSUE TITLE
Initial state network bridge implementation

### ISSUE THREAD

**Issue by mynameisdaniil** [status-im/nimbus-eth1#1902]
Based on existing bridges in `fluffy/tools` implement state network bridge.

To build the bridge: `make portal_bridge`

**Comment by kdeme** [comment]
State bridge file but without actual implementation is here right now: https://github.com/status-im/nimbus-eth1/blob/master/fluffy/tools/portal_bridge/portal_bridge_state.nim#L33 , see TODO there also.

**Comment by web3-developer** [comment]
I believe we can implement the state network bridge without pulling in the EVM or needing to read era1 files by simply calling these JSON-RPC endpoints:
- trace_replayBlockTransactions
- eth_getBlockByNumber

trace_replayBlockTransactions is required to get the state diff for each block and eth_getBlockByNumber is needed to get the withdrawals after the merge. We will also need to calculate minor rewards for premerge separately. Erigon, reth and Besu support trace_replayBlockTransactions and so I believe we should also aim to implement it in Nimbus at some point. 

We will want to use the 'stateDiff' option in the parameters. For example:
```
{
    "jsonrpc": "2.0",
    "method": "trace_replayBlockTransactions",
    "id": 100,
    "params": ["0xAAAAA", ["stateDiff"]]
}
```

The Fluffy state network bridge logic would look something like this:
1. Start from genesis and create an empty state trie backed by rocksdb or another database that supports transactions.
2. For each block, fetch the data from trace_replayBlockTransactions and eth_getBlockByNumber.
3. Apply the state diff to the state trie. Note that we would need to manage additional storage tries for each contract account.
4. After pushing the state updates through the trie/s, collect the list of updated trie nodes and then commit these to the database.
5. Check that the trie state root matches the expected stateRoot value in block header.
6. For each updated trie node, build a proof using the trie state.
7. Convert each trie proof into a portal state network offer.
8. Send each offer to the portal state network by calling portal_stateGossip or perhaps another special purpose custom endpoint defined in Fluffy that supports batching.

**Comment by web3-developer** [comment]
The initial implementation of the state network bridge is now done. In it's current state it is able to sync state by connecting to an execution client that supports the trace_replayBlockTransactions JSON-RPC endpoint (erigon, reth, besu) and then pulls out the proofs for the updated state of each block, converts to the portal state offer format and then sends these offers into a connected portal client (such as Fluffy) over the portal_stateGossip JSON-RPC endpoint.

The next steps are to integrate the portal bridge into Nimbus as a feature that can optionally be enabled. This way the state bridge can seed the portal network while Nimbus syncs and can re-use the existing state building code built into Nimbus.

**Comment by kdeme** [comment]
Some brief documentation on how to set the bridge up would be nice to have here: https://fluffy.guide/history-content-bridging.html

**Comment by web3-developer** [comment]
> Some brief documentation on how to set the bridge up would be nice to have here: https://fluffy.guide/history-content-bridging.html

Sure, I'll make a note to add some documentation shortly.
