### ISSUE TITLE
AccountsCache not being cleared

### ISSUE THREAD

**Issue by web3-developer** [status-im/nimbus-eth1#2083]
See the discussion here for some context:
https://github.com/status-im/nimbus-eth1/pull/2072#discussion_r1524257286

The AccountsCache type holds a cache in memory of the accounts and storage slots which have recently been accessed. This data structure should periodically be cleared in order to avoid memory bloat. Currently the call to persist in the process block function will check if ClearCache is set in the VM flags:
`db.persist(clearEmptyAccount, ClearCache in vmState.flags)`

The VM flag is currently not set anywhere in the code base and therefore the AccountsCache is never cleared. Perhaps the flag should be set by the synchronizer(snap, full, or beacon sync).

**Comment by arnetheduck** [comment]
A new cache is created every time a ledger is created which happens every time a new vmstate is created which happens often enough: 

* https://github.com/status-im/nimbus-eth1/blob/bda760f41dac22f66c9a3ffa56d25bd2f274f4d1/nimbus/db/ledger/accounts_ledger.nim#L145

* https://github.com/status-im/nimbus-eth1/blob/bda760f41dac22f66c9a3ffa56d25bd2f274f4d1/nimbus/evm/state.nim#L76
