### ISSUE TITLE
Nightly build CI regression

### ISSUE THREAD

**Issue by jangko** [status-im/nimbus-eth1#2114]
Nightly build CI failed with this error message

```text
/usr/lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: cannot find -lrocksdb
collect2: error: ld returned 1 exit status
```

https://github.com/status-im/nimbus-eth1/actions/runs/8463037331

ping @web3-developer

**Comment by web3-developer** [comment]
Thanks @jangko , I'm looking into it.

**Comment by web3-developer** [comment]
This is one is now fixed. See here: https://github.com/status-im/nimbus-eth1/actions/runs/8469655180

The changes to the linking flags in the nim-rocksdb library caused the build to break. Had to update the flags to correct the issue.
