### ISSUE TITLE
Avoid use of nimbus db/core_db in Fluffy

### ISSUE THREAD

**Issue by kdeme** [status-im/nimbus-eth1#2146]
The Fluffy code has evolved so that it currently uses the db/core_db functionality for PMT building (required for validation in history network). This module is very much overkill and causes Fluffy to require many parts from nimbus.

This code could be reworked to avoid relying on this nimbus code and for example use the basic PMT implementation with the MemoryDB.

**Comment by web3-developer** [comment]
Changes implemented here: https://github.com/status-im/nimbus-eth1/pull/2152

**Comment by web3-developer** [comment]
The last references to CoreDb have been removed from the tests in Fluffy in my latest PR here: https://github.com/status-im/nimbus-eth1/pull/2170
