### ISSUE TITLE
Fluffy shouldn't allow running multiple instances from the same data directory

### ISSUE THREAD

**Issue by web3-developer** [status-im/nimbus-eth1#2157]
Fluffy doesn't fail or show any error message when starting a second Fluffy instance pointing to the same data directory. The `--data-dir` parameter is also not a required parameter and will use the default directory if not specified therefore it is rather easy for a user to not supply it and mistakenly run multiple instances pointing to the same location.

We should create a lock file on startup in the data directory so that if a second instance is started pointing to the same location it can read the lock file and shutdown with a error message to let the user know the root cause.

**Comment by kdeme** [comment]
This got implemented in https://github.com/status-im/nimbus-eth1/pull/2647
