### ISSUE TITLE
Add support for Portal testnet

### ISSUE THREAD

**Issue by kdeme** [status-im/nimbus-eth1#2206]
The portal testnet (currently unnamed still) got added here as an cli option: https://github.com/status-im/nimbus-eth1/pull/2204

It is however not supported/implemented yet. 

For supporting this we need:
- bootstrap nodes for testnet: Probably should create another vendor repository with all testnet config in there
- need a mapping to different protocol ids per subnetwork for the tesnet, they are being defined here: https://github.com/ethereum/portal-network-specs/pull/258

**Comment by web3-developer** [comment]
Links here: 
https://github.com/ethereum/portal-network-specs/blob/master/portal-wire-protocol.md#angelfood-identifiers
https://github.com/ethereum/portal-network-specs/blob/master/bootnodes.md#bootnodes-angelfood

**Comment by kdeme** [comment]
So we currently have as cli options: 
- `--portal-network`
- `--networks`
- and the deprecated `--network`, which does the same as `portal-networks`

This move was done to be inline with Trin.

The idea now would be to change this to:
- `--portal-subnetworks` and `--network`
  - Where `--portal-subnetworks` would have as set `{beacon, history, state}` to enable or not
- And  `--network` would select any active Portal Network: currently just `mainnet` and `angelfood` are options.
  - It should select the correct bootstrap nodes
  - And it should map the right protocol ids to the right (enabled) networks. It should be noted that testnets in the future might work on different than mainnet Ethereum data. E.g. in the future we might have a testnet working with Sepolia data. This would mean that it wouldn't only select the protocol IDs per network, but also Ethereum testnet config (but this change doesn't need to be added now, but should be something to work towards to be selective at runtime).

**Comment by kdeme** [comment]
There is currently a repo that holds the mainnet config (which isn't much, accumulator, historical_roots and bootstrap nodes).

Considering that this data is the same except for the bootstrap nodes, I'm inclined to keep using this same repository for angelfood.

**Comment by kdeme** [comment]
And then the protocol ids are currently just a const in each *_network.nim file.

Could move them to 1 nim file, or a yaml/json file that gets read at compile time. But I'm thinking that it might be better to split these per portal network and always have a repo with same dir structure (Which would go against what I suggested regarding the bootstrap nodes above).

**Comment by web3-developer** [comment]
> So we currently have as cli options:
> 
> * `--portal-network`
> * `--networks`
> * and the deprecated `--network`, which does the same as `portal-networks`
> 
> This move was done to be inline with Trin.
> 
> The idea now would be to change this to:
> 
> * `--portal-subnetworks` and `--network`
>   
>   * Where `--portal-subnetworks` would have as set `{beacon, history, state}` to enable or not
> * And  `--network` would select any active Portal Network: currently just `mainnet` and `angelfood` are options.
>   
>   * It should select the correct bootstrap nodes
>   * And it should map the right protocol ids to the right (enabled) networks. It should be noted that testnets in the future might work on different than mainnet Ethereum data. E.g. in the future we might have a testnet working with Sepolia data. This would mean that it wouldn't only select the protocol IDs per network, but also Ethereum testnet config (but this change doesn't need to be added now, but should be something to work towards to be selective at runtime).

@kdeme Given that we want to use --portal-subnetworks and --network as command line options, should we keep and deprecate --portal-network and --networks? --network already exists as deprecated, so should un-deprecate it and make this the main option?

**Comment by web3-developer** [comment]
> And then the protocol ids are currently just a const in each *_network.nim file.
> 
> Could move them to 1 nim file, or a yaml/json file that gets read at compile time. But I'm thinking that it might be better to split these per portal network and always have a repo with same dir structure (Which would go against what I suggested regarding the bootstrap nodes above).

@kdeme I think the protocol ids should be in the code, hard coded just like the rest of the types which are defined in the spec. We can map the network startup parameters to the various protocol ids. 

In terms of the repo structure, maybe we could go with different repo when the data stored in the network is different. For example if the network stores sepolia data then it would be a different repo but use the same repo for all networks with mainnet data. Does this sound ok?

**Comment by kdeme** [comment]
> In terms of the repo structure, maybe we could go with different repo when the data stored in the network is different. For example if the network stores sepolia data then it would be a different repo but use the same repo for all networks with mainnet data. Does this sound ok?

If we keep the protocol ids in code, then yes, I think sticking with one repo for all mainnet networks is good. It's a bit silly to make an extra repo for just the bootstrap nodes.

**Comment by kdeme** [comment]
> should we keep and deprecate `--portal-network` and `--networks` options? `--network` already exists as deprecated, so should we un-deprecate it and make this the main option?

Yes and yes.

**Comment by web3-developer** [comment]
Changes are ready for review, in this PR: https://github.com/status-im/nimbus-eth1/pull/2383
