### ISSUE TITLE
Impossible to produce blocks with `forkchoiceUpdated`

### ISSUE THREAD

**Issue by tersec** [status-im/nimbus-eth1#2588]
`master` and https://github.com/status-im/nimbus-eth1/pull/2423 have the same issue

If it already knows about the block:
https://github.com/status-im/nimbus-eth1/blob/0723464928517741bf75440d3bdc6c1644849703/nimbus/beacon/api_handler/api_forkchoice.nim#L154-L163

then it returns and never processes the payload attributes to trigger payload generation later on in that function:
https://github.com/status-im/nimbus-eth1/blob/0723464928517741bf75440d3bdc6c1644849703/nimbus/beacon/api_handler/api_forkchoice.nim#L189-L210

**Comment by jangko** [comment]
> Client software MAY skip an update of the forkchoice state and MUST NOT begin a payload build process if forkchoiceState.headBlockHash references a VALID ancestor of the head of canonical chain, i.e. the ancestor passed [payload validation](https://github.com/ethereum/execution-apis/blob/v1.0.0-beta.4/src/engine/paris.md#payload-validation) process and deemed VALID. In the case of such an event, client software MUST return {payloadStatus: {status: VALID, latestValidHash: forkchoiceState.headBlockHash, validationError: null}, payloadId: null}.

This is what the spec says.
