### ISSUE TITLE
rpc can't server state based data until persisted

### ISSUE THREAD

**Issue by advaita-saha** [status-im/nimbus-eth1#2700]
When the blocks are in memory and is not persisted to the database, during that time rpc requests raise an exception due to 
https://github.com/status-im/nimbus-eth1/blob/9b666860db290f9d249fc4df80581fe6375d78d6/nimbus/rpc/server_api.nim#L60-L66

One of the ways is to replay the state, but on every rpc request state getting replayed might be a bad idea.
This also directly affects the working of `eth_getTransactionCount` endpoint raising an exception and stopping the `blob-spammer` of kurtosis

**Comment by arnetheduck** [comment]
These requests need to be routed to forkedchainref which will keep a version of the state for each known unpersisted state in memory - for now, that involves a replay, but that should be easy to switch to a list of "known heads".
