### ISSUE TITLE
payload with blob : INVALID

### ISSUE THREAD

**Issue by advaita-saha** [status-im/nimbus-eth1#2751]
When a payload with blob is there, it is getting rejected
`
INF 2024-10-18 07:42:05.624+00:00 execution payload invalid from EL client newPayload topics="gossip_blocks" executionPayloadStatus=INVALID executionPayload="(parent_hash: \"309b299e\", fee_recipient: \"8943545177806ed17b9f23f0a21ee5948ecaa776\", state_root: \"c24b5616\", receipts_root: \"80a83e7d\", prev_randao: \"7098efd0\", block_number: 30, gas_limit: 29133471, gas_used: 84000, timestamp: 1729237325, extra_data: \"\", base_fee_per_gas: \"18489556\", block_hash: \"e9dda6a5\", num_transactions: 4, num_withdrawals: 0, blob_gas_used: \"0\", excess_blob_gas: \"0\")" blck="(blck: (slot: 47, proposer_index: 46, parent_root: \"6f5b6cf9\", state_root: \"bec7c519\", eth1data: (deposit_root: d70a234731285c6804c2a4f56711ddb8c82c99740f207854891028af34e27e5e, deposit_count: 0, block_hash: e2fcaff0592b123e48445f690b09fc132b0b8d770984a27072ec4c3aad392425), graffiti: \"1-nimbus-nimbus\", proposer_slashings_len: 0, attester_slashings_len: 0, attestations_len: 18, deposits_len: 0, voluntary_exits_len: 0, sync_committee_participants: 512, block_number: 30, block_hash: \"0xe9dda6a589397173ccd1594dee2302381bfa0ad11acf76ba83ac956c76ced73f\", parent_hash: \"0x309b299ebd8a262a032c6b29df653d8e0363af055621eb31b6c7c267f606db70\", fee_recipient: \"0x8943545177806ed17b9f23f0a21ee5948ecaa776\", bls_to_execution_changes_len: 0, blob_kzg_commitments_len: 4), signature: \"98506d91\")"
`
-> From kurtosis assertor blob transaction test

**Comment by advaita-saha** [comment]
Issue when payload is sent EL to CL

**Comment by advaita-saha** [comment]
Exact error isolated 
```bash
NTC 2024-10-18 16:40:07.080+00:00 Failed to import block                     hash=0xf6be0c5ef8aabd3c6379062e3d5dc89fab8e791c468582a3b6103103b2c27f7b number=19 error="calculated blobGas not equal header.blobGasUsed"
```

**Comment by advaita-saha** [comment]
Block production issue.
When transactions are in the txpool with blobs, and vmState is used to calculate the `blobGasUsed` it always returns `0`. Thus a wrong payload is generated with the `fcu` call with attributes

**Comment by jangko** [comment]
looks like when doing txpool refactoring, the `blobGasUsed` calculation in txpool is somehow removed. and there is no test covering this case.
