### ISSUE TITLE
Support Gas costs and balance >= 2^31 on 32-bit

### ISSUE THREAD

**Issue by mratsim** [status-im/nimbus-eth1#41]
#40 is introduce native integer for gas prices and balances via int64.

Internally it uses [`toInt` proc from stint](https://github.com/status-im/nim-stint/blob/8e25b30209e951bcabfc2d1cd97ef0b971554648/stint/io.nim#L64-L66) implemented as follow:

```Nim
func toInt*(num: Stint or StUint): int {.inline.}=
  # Returns as int. Result is modulo 2^(sizeof(int)
  num.data.least_significant_word.int
```

On 32-bit, int32 would be returned instead of int64.

TODO: introduce a `toInt64` conversion in Stint

Optionally, `toInt64` might be wrapped in Nimbus in a `toGasInt` proc that will add logging and range check for example to make sure a gas value on the stack (uint256) is not over 2^63 - 1 before conversion.

**Comment by jangko** [comment]
this has been long fixed. closing
