### ISSUE TITLE
Implement a transaction pool

### ISSUE THREAD

**Issue by zah** [status-im/nimbus-eth1#469]
The main responsibility of the transaction pool is keeps track of the status of locally created transactions, detecting if they are included in a block (mined) or rolled back on re-orgs.

**Comment by acolytec3** [comment]
Is this still a needed item? Was thinking about taking a stab at it

**Comment by zah** [comment]
Yes, but since we haven't taken the time to write a spec or development plan for this, the first step would be to create one. The transaction pool in the other clients can serve as a reference to some extent, but one key difference is that we are not interested in mining at this point, so we only want to cover the responsibilities listed above.

As a first step, we can sponsor 3 hours of work for researching and proposing a rough step-by-step plan for what needs to be implemented and integrated in Nimbus. The outcome will be posted in this issue. Once approved, we'll set a budget and the work can start.

Alternatively, @jangko can help by formulating the plan.

**Comment by acolytec3** [comment]
Okay, I'll take a look at geth and parity. I skimmed the geth [light client](https://github.com/ethereum/go-ethereum/blob/c2c4c9f1e5f887058285c1299d250899fe0f7d89/light/txpool.go) implemention and it seems like maybe a good model based on what is described in the issue.

**Comment by jangko** [comment]
We have a working txpool and we have wired it with other subsystems.
