### ISSUE TITLE
Syncing with testnets

### ISSUE THREAD

**Issue by jangko** [status-im/nimbus-eth1#473]
* [x] add genesis data for: Ropsten, Rinkeby, Kovan, and Goerli
* [x] modify the VM a bit so we can sync with those testnet
* [ ] add difficulty test for testnet

because some of them using different consensus engine(clique) and not using the ethash, block finalization for them need to wait until we have clique implementation.

* current status: nimbus can sync with Goerli testnet

**Comment by jlokier** [comment]
Time has marched on, and we cannot sync to Goerli testnet any more.

**Comment by tersec** [comment]
None of these testnets is alive/relevant anymore.
