### ISSUE TITLE
Implement Clique PoA consensus engine

### ISSUE THREAD

**Issue by jangko** [status-im/nimbus-eth1#474]
Kovan, Rinkeby and Goerli are using this engine

**Comment by jangko** [comment]
we have to push this forward.
after examining the hive/rpc category, some of the test cases depend on PoA to quickly mining a random(?) block.

the way hive/rpc test cases constructed makes this feature become more important.
each of hive/rpc test cases are not consist of single rpc call, but a series of rpc call which can return different value.

because of this dynamic/algorithmic test nature, we need Clique implementatation even if not complete, it should able to mine a block. and then we can use it to test other part of rpc.

**Comment by jlokier** [comment]
It seems there are really two problems: Validating PoA, and mining PoA.  It is certainly possible to do the former without the latter, the same way we validate PoW without mining PoW currently. Does `hive/rpc` use both of them?

**Comment by jangko** [comment]
yes, hive/rpc require both of them

**Comment by jlokier** [comment]
Is the mining PoA functionality only used for passing Hive tests, and is the code for mining large or is it trivial?

As we discussed last week, there is no need to pass Hive tests for functionality that Nimbus Eth1 doesn't intend to provide to end users - i.e. mining.  For these it's better to say "we decided these Hive tests are not applicable to Nimbus Eth1".  And actually it's not really useful to write large amounts of code just to pass tests for functionality that will never be used.

We do need block construction for the eth2 merge.  But that doesn't use any Clique/PoA logic.

**Comment by jangko** [comment]
@mjfh, what is the status of this issue, can we close it and start using clique-code in RPC?

**Comment by mjfh** [comment]
Mostly done.

Did some statistics, fixed/tuned some unnecessary time consuming actions, and polished the API.

Should be open for review later this afternoon.

**Comment by jangko** [comment]
fixed by #815
