### ISSUE TITLE
Can't join local network, no value found in genesis block

### ISSUE THREAD

**Issue by DanielVF** [status-im/nimbus-eth1#548]
I'm trying to add a nimbus eth-1 node to a local test blockchain I have setup running multiple Geth nodes.

When I launch nimbus, it is immediately failing with:

_No value found in genesis block for tid=632482 file=config.nim:354 fieldNamegensym105620202=eip150Hash_

Here's my genesis.json, which is working for the geth nodes:

```
{
"config": {
"chainId": 1234,
"homesteadBlock": 0,
"eip155Block": 0,
"eip150Block": 0,
"eip158Block": 0
},
"alloc": {},
"difficulty" : "0x20000",
"gasLimit" : "0x8880000"
}
```

I'm using a newly built nimbus, git hash: bf320ed172f74f60fd274338e82bdc9ce3520dd9

Command line parameters build/nimbus --nodiscover --networkid:1234 --bootnodes:{snip} --customnetwork:../genesis.json

From the logging on the other nodes in the local network, the nimbus node is exiting before it makes a connection to any other node.

**Comment by DanielVF** [comment]
Adding an "eip150Hash" field to my genesis.json cleared up this error, however I'm now stumped with:

_No value found in genesis block for        tid=1183798 file=config.nim:354 fieldName`gensym107215202=nonce_

I'm still seeing this message even after adding a nonce field to genesis.json:

{
"config": {
  "chainId": 1234,
  "homesteadBlock": 0,
  "eip155Block": 0,
  "eip150Block": 0,
  "eip158Block": 0,
  "eip150Hash":"BB",
  "nonce":"0x00",
},
"alloc": {},
"difficulty" : "0x20000",
"gasLimit"   : "0x8880000"
}

**Comment by jangko** [comment]
`nonce` should be outside `config`. The json format should something like this:

```json
{
"config": {
"chainId": 1234,
"homesteadBlock": 0,
"eip155Block": 0,
"eip150Block": 0,
"eip158Block": 0,
"eip150Hash":"0x0000000000000000000000000000000000000000000000000000000000000000",
},
"nonce":"0x00",
"mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
"alloc": {},
"difficulty" : "0x20000",
"gasLimit" : "0x8880000"
}
```
