### ISSUE TITLE
hive requirement, echoes the enode of the running instance

### ISSUE THREAD

**Issue by jangko** [status-im/nimbus-eth1#569]
there is no standardization in this matter, most of other clients out there are using client specific non-standard RPC to retrieve the enode.

what should be returned by the RPC call also not standardized, only example.

but in order to simplify things, we can just implement this similar RPC API. whatever the name we like to choose.

**Comment by jlokier** [comment]
In general for most RPC calls, if it's not specific to Nimbus, I would suggest use whatever RPC Geth uses, for maximum compatibility with various 3rd party clients. That is, unless the eth1-JSON-RPC standardisation effort has recommended a different RPC, even then it makes sense to report as Geth does too.
