### ISSUE TITLE
Very long Control-C delay during first minute or so is annoying

### ISSUE THREAD

**Issue by jlokier** [status-im/nimbus-eth1#585]
During the first minute or so after starting `nimbus`, pressing control-C is trapped and has no effect for a rather long time. This is very annoying, if you just started something to debug then want to do something else. It's easily worked around by Control-Z then killing the process, but this is still a poor experience.

After the first minute or so, control-C exits reasonably fast, so it can do this.

**Comment by jlokier** [comment]
The cause of this unresponsiveness is slow sequential initialisation in `nimbus.start`.

There are a number of steps which take time depending on network activity, during which Control-C is ignored.  The worst of these is the discovery phase, which effectively runs as a "foreground task" for some minutes before allowing the sync phase to be initialised.  This `waitFor` during initialisation takes several minutes: https://github.com/status-im/nimbus-eth1/blob/6d4205b0b07b35ab9c76ab2d14733c67127aa042/nimbus/nimbus.nim#L162

There are other steps which are usually fast, but could be slow if you are unlucky (e.g. UPNP/NAT-PMP configuration).  So the issue isn't one single `waitFor`.  All steps should be abortable.

Async cancellation tokens (set by the Control-C signal) are a general solution to this problem, but that may require a change to Chronos.  A more pragmatic (but ugly) immediate solution is to make P2P `connectToNetwork` busy-wait with short timeouts and check for the Control-C condition.

**Comment by jlokier** [comment]
Note, in configurations where no peers are successfully connected to, the `waitFor` doesn't return.

This happens when static nodes are set and discovery is disabled.  If the static node is down or refuses connection, Nimbus Eth1 doesn't retry, `connectToNetwork` never completes, and Control-C doesn't work no matter how long you wait.  When this happens, 100% of the time you want to use Control-C :-)

**Comment by kdeme** [comment]
Yes, I was having similar issues with the p2p implementation of nim-eth when using it for nim-waku wakunode.

Back then I just did this: https://github.com/status-im/nim-waku/blob/master/waku/v1/node/wakunode1.nim#L61
But it is still flawed in several ways, and the peer management could really use some rework in nim-eth (well it is rather non existent right now)

I'm pretty sure I had created an issue for this back then but can't seem to find it back.
