### ISSUE TITLE
hive: devp2p/eth: implement missing handler of eth protocol

### ISSUE THREAD

**Issue by jangko** [status-im/nimbus-eth1#673]
many of the handlers of eth protocol both in nim-eth and nimbus-eth1 are still empty or maybe buggy.
we need to implement them to pass devp2p/eth tests in hive

**Comment by jlokier** [comment]
Can you expand on this a bit?  Which parts of the eth protocol does Hive exercise, and which versions?

**Comment by jangko** [comment]
hive will relay the test to https://github.com/ethereum/go-ethereum/tree/master/cmd/devp2p/internal/ethtest

from brief glance it looks like ethtest try to connect using `eth/66` first then fallback to `eth/65` or `eth/64`.

some of protocol methods used by ethtest are:

- Status
- GetBlockHeaders
- NewBlock
- NewBlockHashes
- NewPooledTransactionHashes?
- GetBlockBodies
- GetPooledTransactions
- Transactions

not tested methods:
- GetNodeData
- GetReceipts
