### ISSUE TITLE
> transitioning to unittest2

### ISSUE THREAD

**Issue by jangko** [status-im/nimbus-eth1#691]
> transitioning to unittest2

Most of Nimbus-eth1 tests already use unittest2. Only these are still on unittest:

```text
tests/test_rpc.nim
tests/rpcclient/test_hexstrings.nim
tests/test_rpc_whisper.nim
tests/test_graphql.nim
```

_Originally posted by @stefantalpalaru in https://github.com/status-im/nimbus-eth1/issues/332#issuecomment-849596698_

**Comment by jlokier** [comment]
`tests/test_rpc_whisper` is removed by #705.
