### ISSUE TITLE
Implement uTP protocol

### ISSUE THREAD

**Issue by kdeme** [status-im/nimbus-eth1#752]
Issue to implement uTP according to specification here: https://www.bittorrent.org/beps/bep_0029.html

To be used for Portal Network data stream: https://github.com/ethereum/stateless-ethereum-specs/blob/master/discv5-utp.md

Currently only used/specified in state network: https://github.com/ethereum/stateless-ethereum-specs/blob/master/state-network.md#dht-network
Likely also to be used for historical chain data retrieval?

Must be able to integrate easy with discovery v5.1 implementation, which would relate to this issue: https://github.com/status-im/nimbus-eth1/issues/725
Basically, no matter the outcome of that issue, it will likely have to share port / socket with discovery v5

Aside that eventually the uTP implementation needs to integrate well with discv5.1 and fluffy portal protocol, it can be initially developed as a standalone library, but in a way that the underlying transport can easily be changed (UDP, discv5 talkreq messages, perhaps some test mocking, ...).

The first step is to have this uTP implementation running on UDP, so that it can be interop tested with the reference implementation.

Implementation list found:
- Reference implementation: https://github.com/bittorrent/libutp
  - Bulk of the implementation is in: https://github.com/bittorrent/libutp/blob/master/utp_internal.cpp
  - Small application to test interop with: https://github.com/bittorrent/libutp/blob/master/ucat.c
- Other implementation: https://github.com/rtttech/utp
- libtorrent also holds utp implementation: https://github.com/arvidn/libtorrent

I have not found any tests.

**Comment by KonradStaniec** [comment]
Just to confirm (and have it somewhere documented)according to https://github.com/ethereum/stateless-ethereum-specs/issues/66#issuecomment-878547844, uTP will also be used for transport for chain history network in case of larger payloads.

**Comment by kdeme** [comment]
Implementation is happening here: https://github.com/status-im/nim-eth/tree/master/eth/utp

**Comment by KonradStaniec** [comment]
Implementation is now fairly complete and usabl.
