### ISSUE TITLE
Create/Define messages which should be used in blockchain history network

### ISSUE THREAD

**Issue by KonradStaniec** [status-im/nimbus-eth1#761]
As for now it seems we should support messages to get data described in: https://github.com/ethereum/stateless-ethereum-specs/blob/master/portal-network.md#chain-history-headers-blocks-and-receipts i.e

GetHeaderByHash(hash) -> Response(Header, PartialMerkleProof, PartialMerkleProof)
GetBodyByHash(hash) -> Response(BlockBody)
GetReceiptsByHash(hash) -> Response(Receipts)

We should also support messages described in https://notes.ethereum.org/KaMqlqxiQLCWyDoXCUCC4Q:

GetAccumulator(height) -> Response(LeafAccumulator, MasterAccumulator)
GetAccumulatorHash(height) -> Response(AccumulatorHash)

The wire format for those messages is up to definition.
Also most of those messages are to large for single udp packet so using uTP will be obligatory.

**Comment by kdeme** [comment]
Closed as not fully relevant anymore and similar is implemented.
