### ISSUE TITLE
Merge PoA miner/coinbase address calculation in vm_state and clique-ec_recover

### ISSUE THREAD

**Issue by jangko** [status-im/nimbus-eth1#768]
https://github.com/status-im/nimbus-eth1/blob/a0d0e35a706a295d5e2e4328eb461577c62b9049/nimbus/vm/state.nim#L89

https://github.com/status-im/nimbus-eth1/blob/a0d0e35a706a295d5e2e4328eb461577c62b9049/nimbus/vm2/state.nim#L77

https://github.com/status-im/nimbus-eth1/blob/a0d0e35a706a295d5e2e4328eb461577c62b9049/nimbus/p2p/clique/clique_cfg/ec_recover.nim#L54

we have three different places where the PoA miner address is calculated. time to clean it up and use only one calcucator. ping @mjfh.

**Comment by mjfh** [comment]
Good point.

Most part of the _ec_recover.toValue()_ handler can be implemented outside. And the calculation is only dependent on the header (more specifically _extraData_ field.)

Will re-implement it as utils/&lt;something&gt;.nim.

**Comment by jangko** [comment]
fixed by #782, closing
