### ISSUE TITLE
config: prepare PoA engine configuration for upcoming clique and rpc test in hive

### ISSUE THREAD

**Issue by jangko** [status-im/nimbus-eth1#771]
hive simulators have the following flags set:

- rpc simulator:
```text
"HIVE_CLIQUE_PERIOD":     "1",
"HIVE_CLIQUE_PRIVATEKEY": "9c647b8b7c4e7c3490668fb6c11473619db80c93704c70893d3813af4090c39c",
"HIVE_MINER":             "658bdf435d810c91414ec09147daa6db62406379",
```

- smoke/clique:
```text
"HIVE_CLIQUE_PERIOD":     "2",
"HIVE_CLIQUE_PRIVATEKEY": "9c647b8b7c4e7c3490668fb6c11473619db80c93704c70893d3813af4090c39c",
"HIVE_MINER":             "658bdf435d810c91414ec09147daa6db62406379",
```

whatever it means, we need to prepare the cli parser and friends for:
- clique period -- clique only
- clique private key -- clique only, ethash cannot use insecure method to set private key.
- miner address -- common for both clique and ethash

**Comment by mjfh** [comment]
my guess:
- HIVE_CLIQUE_PERIOD: min time distance berw blocks, typically 15s
- HIVE_CLIQUE_PRIVATEKEY: should be initial signer (last 65 bytes of extraData in genesis)
- HIVE_MINER: should be some initial authorised signer (list of is part of  extraData in genesis)

**Comment by mjfh** [comment]
my guess was slightly wrong:
- _privateky_ + _miner_ should be in first mined block
- this is similar to calonical test no 1 (see test_clique/voter-samples.nim)
- so _miner_ is the address derived from _privatekey_ and must be part of genesis (as it is indeed)

**Comment by jangko** [comment]
from other hive clients example:
- HIVE_MINER will activate mining mode using either clique or ethash via cli
- HIVE_CLIQUE_PRIVATEKEY will go to private key vault similar to ethash
- HIVE_CLIQUE_PERIOD will go to chain config.
