### ISSUE TITLE
`--customnetwork:FILE.json` does not work with test network Calaveras using the official file

### ISSUE THREAD

**Issue by jlokier** [status-im/nimbus-eth1#786]
Using this option `--customnetwork:calaveras.json` with or without `--networkid:123` fails to result in a successful connection ot the Calaveras network, because genesis hash, network Id and probably other values are incorrect.

The file `calaveras.json` is the JSON file in the [Calaveras specification](https://github.com/ethereum/eth1.0-specs/blob/master/network-upgrades/client-integration-testnets/calaveras.md).

In network logs some things are clear:

- The `networkId` we are using is zero.  It should be 123. This is visible in the `eth.Status` message, but it's a missing value in the chain config, not the network code.
- The genesis hash we are using is wrong. It should be `eb9233d066c275efcdfed8037f4fc082770176aefdbcb7691c71da412a5670f2` but we have calculated `2893a852a2fdec70cfb74307512489a2880c55703dcb623e3cf51300474af8d4` after setting up the genesis config.
- We have `poaEngine: false`, but this is a PoA network, and is configured as such in the JSON file.

Do we not support this file format?

**Comment by jangko** [comment]
* networkId can be set from `--networkId:123`
* the json file need to be modified a bit. all genesis fields should be put into `genesis`:
```text
{
 "config": { 
   ...
},
 "genesis": {  #  <-  move all genesis fields into here
  ... 
}      
}
```
* configure PoA using json file is not supported yet.
