### ISSUE TITLE
Make distance function in discoveryv5 routing table configurable.

### ISSUE THREAD

**Issue by KonradStaniec** [status-im/nimbus-eth1#797]
According to spec https://notes.ethereum.org/h58LZcqqRRuarxx4etOnGQ, content in state network will be organized around new distance function. To accomodate to that we will  need to be able to swap distance functions in:
https://github.com/status-im/nim-eth/blob/master/eth/p2p/discoveryv5/routing_table.nim#L96

**Comment by kdeme** [comment]
Closed by status-im/nim-eth#392 and bumps
