### ISSUE TITLE
Fluffy ContentDB needs access to total size of stored content

### ISSUE THREAD

**Issue by kdeme** [status-im/nimbus-eth1#871]
[ContentDB](https://github.com/status-im/nimbus-eth1/blob/master/fluffy/content_db.nim#L33) needs access to total size of stored content: Retrieval of the total number of bytes stored.

Approaches:
- Use something sqlite specific, but that would probably include the overhead and also lag behind on deletions, etc.. Aside from the fact that it would be sqlite specific.
- Calculate on layer on top, but that might be less performant.
- ... ?

**Comment by KonradStaniec** [comment]
Added with https://github.com/status-im/nimbus-eth1/pull/987
