### ISSUE TITLE
Add validation of received history content

### ISSUE THREAD

**Issue by kdeme** [status-im/nimbus-eth1#970]
Just as in the devp2p/eth protocol, history content such as block headers, bodies and receipts should be validated.
I think the same rules can be applied as described here:
- https://github.com/ethereum/devp2p/blob/master/caps/eth.md#transaction-encoding-and-validity
- https://github.com/ethereum/devp2p/blob/master/caps/eth.md#transaction-encoding-and-validity
- https://github.com/ethereum/devp2p/blob/master/caps/eth.md#transaction-encoding-and-validity

Most if this should be implemented already in Nimbus. However perhaps not fully reusable as is. In such case, ideally, we could extract the relevant parts to separate file(s) that are usable by both projects. 

Some quick scan:
https://github.com/status-im/nimbus-eth1/blob/cdfcdfc85b5a7202f04ec4778287df3173cd5210/premix/downloader.nim#L97
https://github.com/status-im/nimbus-eth1/blob/295c1409f618f253dd9d1046cd61ddb44c40f7e6/nimbus/transaction.nim#L79

**Comment by KonradStaniec** [comment]
@kdeme I wonder if really we need to validate all this fields ? 

I mean from what i remember we will derive security of our header from this double batched merkele accumulator i.e if the header is part of accumulator it means that it is part of canonical chain and all is fine, and it already passed all validations required to become part of this chain. So maybe one validation required for header is that it indeed has the hash that we asked for.

As far for transactions (and receipts) wouldn't it be enough to check that `header.transactionRoot == mpt(receivedTransactions).root` ? This way we prove that transactions are belonging to header which already determined that is part of canonical chain ?

**Comment by kdeme** [comment]
Yeah, it is possible that most of it is not needed for the history network. I didn't actually go over all the details when I created the issue.

For header it is fairly simply, we just take the hash and compare it with the requested one.

And yes, I think you're right that just checking the txRoot (and also for uncles by the way) should be sufficient. We can't actually validate the "header chain" yet, but it would be sufficient in the future.

For transactions I think the full validation will still be useful for the Transaction Gossip network. Basically validating non included transactions, which is similar to what is described in the links I provided.

**Comment by KonradStaniec** [comment]
implemented validations of headers and bodies in: https://github.com/status-im/nimbus-eth1/pull/983, we can add validation of receipts while working on https://github.com/status-im/nimbus-eth1/issues/977

**Comment by kdeme** [comment]
What is still needed now is validation for block bodies in offer/accept flow and validation for receipts once we add those.

**Comment by kdeme** [comment]
validation for block bodies and receipts is added in here: https://github.com/status-im/nimbus-eth1/pull/1158, so closing this.

To actually check if they are part of canonical chain is part of this issue: https://github.com/status-im/nimbus-eth1/issues/1084
